name: Publish slides

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  publish-slides:
      runs-on: ubuntu-latest

      permissions:
        contents: write
      steps:

        - name: Check out repository
          uses: actions/checkout@v3

        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.5.37
<<<<<<< Updated upstream
            
        - name: Install libcurl4
          run:  sudo apt install libcurl4-openssl-dev
  
        - name: Install Latex
          run:  quarto install tinytex
        
=======
        
        - name: Installs TeX Gyre Heros
          run: |
            echo "ðŸ” Checking for root privileges..."
            if [ "$EUID" -ne 0 ]; then
              echo "âŒ Please run this script as root (use: sudo $0)"
              exit 1
            fi

            echo "âœ… Updating package lists..."
            apt update -y

            echo "ðŸ“¦ Installing TeX Gyre fonts..."
            apt install -y fonts-texgyre

            echo "âœ… Done!"

>>>>>>> Stashed changes
        - name: Render and Publish
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_CI }}
